stages:
  - lint
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-online

eslint:
  extends:
    - .default-cache
  image: node:14.17.0-alpine
  stage: lint
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm i
    - npm run lint

prettier:
  extends:
    - .default-cache
  image: node:14.17.0-alpine
  stage: lint
  variables:
    NODE_VERSION: 14.17.0
  script:
    - npm i
    - npm run check:format

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from '.gitignore'
      --exclude .gitignore
      --exclude .git
      . deploy@139.162.15.161:~/realworld/
    - ssh deploy@139.162.15.161 "pushd ~/realworld && npm i && pm2 restart realworld && popd"