name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Lint source code with ESLint
        run: npm run lint
  
  eslint:
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Lint source code with ESLint
        run: npm run check:format